#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
    echo "ERROR: .env not found. Copy .env.example to .env and fill it in."
    exit 1
fi

set -a
source "$SCRIPT_DIR/.env"
set +a

LGSM_CFG="$PZSERVER_HOME/lgsm/config-lgsm/pzserver/pzserver.cfg"
SERVER_INI="$PZSERVER_HOME/Zomboid/Server/${SERVER_NAME}.ini"

echo "==> Writing LinuxGSM instance config..."
sudo tee "$LGSM_CFG" > /dev/null << EOF
## Auto-generated by configure.sh — do not edit by hand
servername="${SERVER_NAME}"
maxplayers="${MAX_PLAYERS}"
port="${DEFAULT_PORT}"
rconport="${RCON_PORT}"
rconpassword="${RCON_PASSWORD}"
javamemoryinitial="${RAM_INIT_MB}"
javamemorytotal="${RAM_MAX_MB}"
startparameters="-servername ${SERVER_NAME} -adminusername ${ADMIN_USERNAME} -adminpassword ${ADMIN_PASSWORD}"
EOF
sudo chown "$PZSERVER_USER:$PZSERVER_USER" "$LGSM_CFG"
echo "    wrote $LGSM_CFG"

echo "==> Patching server ini..."
sudo python3 - "$SERVER_INI" "$RCON_PASSWORD" "$RCON_PORT" "$MAX_PLAYERS" "$DEFAULT_PORT" "$UDP_PORT" << 'PYEOF'
import sys
from configparser import RawConfigParser

path, rcon_pass, rcon_port, max_players, default_port, udp_port = sys.argv[1:]

with open(path, "r") as f:
    raw = f.read()

if not raw.startswith("[ServerConfig]"):
    raw = "[ServerConfig]\n" + raw

cp = RawConfigParser()
cp.optionxform = lambda o: o
cp.read_string(raw)

cp["ServerConfig"]["RCONPassword"]   = rcon_pass
cp["ServerConfig"]["RCONPort"]       = rcon_port
cp["ServerConfig"]["MaxPlayers"]     = max_players
cp["ServerConfig"]["DefaultPort"]    = default_port
cp["ServerConfig"]["UDPPort"]        = udp_port
cp["ServerConfig"]["DiscordEnable"]  = "false"
cp["ServerConfig"]["DiscordToken"]   = ""
cp["ServerConfig"]["DiscordChannel"] = ""
cp["ServerConfig"]["DiscordChannelID"] = ""

with open(path, "w") as f:
    cp.write(f, space_around_delimiters=False)

print(f"    patched {path}")
PYEOF

echo "==> Installing weekly reboot script..."
sudo cp "$SCRIPT_DIR/weekly-reboot.sh" "$PZSERVER_HOME/weekly-reboot.sh"
sudo chmod +x "$PZSERVER_HOME/weekly-reboot.sh"
sudo chown "$PZSERVER_USER:$PZSERVER_USER" "$PZSERVER_HOME/weekly-reboot.sh"

echo "==> Installing cron job..."
sudo cp "$SCRIPT_DIR/pzserver-reboot.cron" /etc/cron.d/pzserver-reboot

echo "==> Applying sysctl tuning..."
sudo cp "$SCRIPT_DIR/99-pzserver.conf" /etc/sysctl.d/99-pzserver.conf
sudo sysctl -p /etc/sysctl.d/99-pzserver.conf

echo "==> Applying file descriptor limits..."
sudo cp "$SCRIPT_DIR/pzserver-limits.conf" /etc/security/limits.d/pzserver.conf

echo "==> Installing systemd unit..."
sudo cp "$SCRIPT_DIR/pzserver.service" /etc/systemd/system/pzserver.service
sudo systemctl daemon-reload
sudo systemctl enable pzserver
echo "    enabled pzserver.service"

echo "==> Generating gateway nftables config from template..."
sed \
    -e "s|\${MAILMAN_PUBLIC_IFACE}|${MAILMAN_PUBLIC_IFACE}|g" \
    -e "s|\${ELITE_TAILSCALE_IP}|${ELITE_TAILSCALE_IP}|g" \
    -e "s|\${DEFAULT_PORT}|${DEFAULT_PORT}|g" \
    -e "s|\${UDP_PORT}|${UDP_PORT}|g" \
    -e "s|\${RCON_PORT}|${RCON_PORT}|g" \
    "$SCRIPT_DIR/gateway/pz-forward.nft.template" > "$SCRIPT_DIR/gateway/pz-forward.nft"
echo "    generated gateway/pz-forward.nft (deploy this to gateway at /etc/nftables.d/pz-forward.nft)"

echo ""
echo "Done. Run 'sudo systemctl restart pzserver' to apply."
